services:
  # container db
  db22:
    # container name
    container_name: db22
    image: postgres:lates
    # env db
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test2
    # port db
    ports:
      - 5432:5432
    # volume db
    volumes:
      - data:/var/lib/postgresql
  # container app
  go:
    container_name: go22
    environment:
      - DB_HOST=db22
      - DB_USER=postgres
      - DB_PASSWORD=postgrespw
      - DB_PORT=5432
      - DB_NAME=test2
    ports:
      - 8083:8081
    image: myapp2
    depends_on:
      - db22

volumes:
  data:
